[project]
name = "gubchat"
description = "Gubchat is a chat client for twitch"
version = "0.1.1"
authors = [
    { name = "Douglas", email = "hashy.software@gmail.com" }
]
dependencies = [
    "aiohttp >= 3.8.5",
    "websockets >= 11.0.3",
    "kivy >= 2.2.1",
    "kivymd >= 1.1.1",
]

[tool.isort]
profile = "black"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
gubchat = "gubchat.main:main"

[project.optional-dependencies]
dev = []

